### ISSUE TITLE
baseURL support

### ISSUE THREAD

**Issue by guybedford** [capaj/chokidar-socket-emitter#1]
Surely in order to support baseURL, this would need to have knowledge of the jspm configuration file etc?

**Comment by capaj** [comment]
@guybedford PR https://github.com/capaj/chokidar-socket-emitter/pull/2 should be getting it's config from package.json if no other is specified.
Is that allright? Or should I rather use Systemjs API for this?

**Comment by guybedford** [comment]
Note it should be `pjson.jspm.directories.baseURL || pjson.directories.baseURL`. The idea is for `directories.baseURL` to possibly be a convention for more than just jspm.

**Comment by capaj** [comment]
fixed in ae2fb87e and b369184d
