### ISSUE TITLE
Undefined "package.json".

### ISSUE THREAD

**Issue by m-a-r-c-e-l-i-n-o** [capaj/chokidar-socket-emitter#18]
I'm using "chokidar-socket-emitter" in conjunction with "systemjs-hot-reloader@0.5.6". I used to start the  "chokidar-socket-emitter" globally, but have now switched to initializing it within a node server (ran by jspm (jspm run {my server file}). 

I import it like so:

```
import chokidarEvEmitter from 'chokidar-socket-emitter'
chokidarEvEmitter( { app: server } )
```

Everything works perfectly expect that the following error is thrown by "systemjs-hot-reloader@0.5.6":
`Uncaught TypeError: Cannot read property 'jspm' of null hot-reloader.js:41`.

Upon further investigation, it's clear that the issue originates in the "chokidar-socket-emitter@0.5.0/server.js" file, lines 10-13:
`try {
    pjson = require(path.join(opts.dir || path.dirname(require.main.filename), 'package.json'))
  } catch (err) {
    error = err
  }`

Without supplying the "dir" parameter, the require fails and throws this error:
`TypeError: Cannot read property 'filename' of undefined`

Supplying the "dir" parameter, the require fails and throws this error:
`[Error: Module /home/marcbraulio/Projects/jspm-test-v3/package.json not declared as a dependency of file:///home/marcbraulio/Projects/jspm-test-v3/jspm_packages/npm/chokidar-socket-emitter@0.5.0/server.js]`

Explicitly calling:
`require("/home/marcbraulio/Projects/jspm-test-v3/package.json")`
results in:
`SyntaxError: Unexpected token :`
...somehow it fails to parse that json file, but parses:
`require("/home/marcbraulio/Projects/jspm-test-v3/jspm_packages/npm/chokidar-socket-emitter@0.5.0/package.json"`)
...just fine (very confused about that, would love an explanation).

Also, not sure how/why
`require(path.join(opts.dir || path.dirname(require.main.filename), 'package.json'))` 
which renders to (with the supplied opts.dir):
`require("/home/marcbraulio/Projects/jspm-test-v3/package.json")`
throws a different error than when you just call:
`require("/home/marcbraulio/Projects/jspm-test-v3/package.json")`
explicitly.

How can this be resolved and what's the reason for this inconsistent require/path/error behavior? Is it a jspm (0.17.0-beta.12) problem?

Thank you for your time.

**Comment by capaj** [comment]
@m-a-r-c-e-l-i-n-o this is a bug caused by the fact that I forgot to take into consideration the fact that some people might not have their package.json found when I wrote this line:
https://github.com/capaj/chokidar-socket-emitter/blob/29e7ace5cf1570a4c1d6732f09989268d197f5b2/server.js#L66

I have fixed that in release 0.5.1 by disabling this socket.io handler if pjson doesn't exist.

**Comment by m-a-r-c-e-l-i-n-o** [comment]
Thank you for the quick response. Have you considered that by resolving it that way, you are stripping the "Programatic" version of this feature: https://github.com/capaj/systemjs-hot-reloader/blob/master/hot-reloader.js#L58 ? The require for the "Programatic" will always fail, so it's more of a "require vs failure to require" issue than a "package.json vs no package.json" issue. Is there really no way to get that require working properly for both the "CLI" and "Programatic" versions?

**Comment by capaj** [comment]
@m-a-r-c-e-l-i-n-o programmatic will only fail when it can't find package.json. You're right that we could improve on that. Locating package.json is not very clever. I will take a look into improving that and I will also add a warning when we don't have package.json required succesfully.

**Comment by m-a-r-c-e-l-i-n-o** [comment]
Sorry, I don't think I explained myself well enough. My main concern is with the "Programmatic" version when being ran by jspm (i.e. `jspm run my-node-server-file.js`). When running  the "Programmatic" version via plain ol' node/npm (i.e. `node my-node-server-file.js`), everything behaves as expected. It's true that for the "`node my-node-server-file.js` - Programmatic" we can do a little bit of a better job finding the JSON (since it's path starts at the script's location), but that can easily be resolved by passing the appropriate "dir" parameter. The real issue is that when doing `jspm run my-node-server-file.js`, even with the correct "dir" parameter, the require fails. It fails every time for anything outside the "jspm_packages/npm/chokidar-socket-emitter" directory, so my "package.json" located at the root of my project, will never be required. Seems like there is an inconsistency with the way jspm treats require functions that would need to be accounted for. Not sure if it's a jspm bug, or if there is a proper way of handling these cases that I'm not aware of. Does this help clarify my concern?
