### ISSUE TITLE
When chokidar-socket-emitter running via npm it fails

### ISSUE THREAD

**Issue by sokolovstas** [capaj/chokidar-socket-emitter#21]
Missing error handler on `socket`.
TypeError: fn is not a function
    at Socket.<anonymous> (/Volumes/HDD/Projects/angular2/crack/node_modules/chokidar-socket-emitter/server.js:62:7)

I belive that correct will be

```
socket.on('package.json', function (fn) {
      fn(pjson)
    })
```

**Comment by capaj** [comment]
@sokolovstas you were using old version of systemjs-hot-reloader. See my earlier comment: https://github.com/capaj/chokidar-socket-emitter/issues/14#issuecomment-186855175

Sorry that I did not get to this sooner.
