### ISSUE TITLE
Symlink doesn't trigger change detection

### ISSUE THREAD

**Issue by VRspace4** [capaj/chokidar-socket-emitter#22]
Hi, it appears chokidar-socket-emitter doesn't pick up file changes from within a symlinked folder. Any way I could get this to work? Thanks in advance.

**Comment by capaj** [comment]
Try

```
chokidarEvEmitter({port: 8090, path: '.', chokidar: {usePolling: true}})
```

**Comment by VRspace4** [comment]
I'm currently using it with option, `app: server.server`. I've tried the following, inside `server.js`:

```
const http:server = require('http-server');
...
var chokidarEvEmitter = require('chokidar-socket-emitter');
chokidarEvEmitter({app: server.server, port: 9089, path: '.', chokidar: {usePolling: true}});
...
```

I was able to load the page in the browser, but it still doesn't detect changes from files inside the symlinked folder.

**Comment by VRspace4** [comment]
I found a solution to this based on a suggested change from, https://github.com/capaj/chokidar-socket-emitter/pull/23:

I made the following change to `/node_modules/chokidar-socket-emitter/server.js` at `Line 46`:
From
`var watcher = chokidar.watch(pathToWatch, chokidarOpts)`
To
`var watcher = chokidar.watch(path.resolve(pathToWatch), chokidarOpts)`

I'm not sure if this affects anything else, but so far it's working great with symlinked folders!
