### ISSUE TITLE
Allow custom ignore paths for chokidar

### ISSUE THREAD

**Issue by peterjuras** [capaj/chokidar-socket-emitter#25]
Hi!

I understand that watching jspm_packages creates issues on many systems, but my workflow depends on linking a lot of jspm packages and testing them inside a larger "sandbox", because they are often not able to run on their own.

Would you be open to an override property/option to allow the passing of a custom ignored paths array? I could create a pull request if you would be interested.

**Comment by capaj** [comment]
I think you should be able to do it now-

``` javascript
chokidarEvEmitter({port: 7090, path: '.', ignore: []})
```

Give that a try and let me know if that works for you.

**Comment by peterjuras** [comment]
Thanks for the quick reply!

I overlooked the passthrough of chokidar options, so thanks for the hint! I had to put it in the [chokidar property](https://github.com/capaj/chokidar-socket-emitter/blob/master/server.js#L44) to get it to work though:

``` js
chokidarEvEmitter({ port: 7090, path: '.', chokidar: { ignored: [] })
```

After that, I can see that the ignored options are being replaced when passed on to chokidar.
