### ISSUE TITLE
default ignored dirs no longer ignored after path resolution

### ISSUE THREAD

**Issue by peterjuras** [capaj/chokidar-socket-emitter#26]
[This commit](https://github.com/capaj/chokidar-socket-emitter/commit/9f9aeb34f16eafc9918c20461e42b84561d513c5) changed the path resolution.

Afterwards, files within node_modules and probably jspm_packages are no longer ignored by default, because they don't lie within the root/baseURL directory anymore:

```
C:\Source\misc\choki-test> npm i -g chokidar-socket-emitter@0.5.2
C:\Source\misc\choki-test> chokidar-socket-emitter
chokidar watching  C:\Source\misc\choki-test
chokidar-socket-emitter listening on 5776
// Changing file within node_modules emits no event (correct default behavior)
^CTerminate batch job (Y/N)?


C:\Source\misc\choki-test> npm i -g chokidar-socket-emitter@0.5.3
C:\Source\misc\choki-test> chokidar-socket-emitter
chokidar watching  C:\Source\misc\choki-test
chokidar-socket-emitter listening on 5776
File  C:/Source/misc/choki-test/node_modules/brace-expansion/package.json  emitted: change
File  C:/Source/misc/choki-test/node_modules/brace-expansion/package.json  emitted: change
File  C:/Source/misc/choki-test/node_modules/brace-expansion/package.json  emitted: change
File  C:/Source/misc/choki-test/node_modules/brace-expansion/package.json  emitted: change
```

This also probably leads to [systemjs-hot-reloader](https://github.com/capaj/systemjs-hot-reloader) no longer recognizing the changed files.

**Comment by capaj** [comment]
@peterjuras hmm that's not what we want. Testing on my Ubuntu machine this works-changing files in `node_modules` is ignored. Problems is that it does not work for `jspm_packages` folder.

Will revert in `0.5.4`
