### ISSUE TITLE
Make logging optional

### ISSUE THREAD

**Issue by sv2dev** [capaj/chokidar-socket-emitter#27]
At the moment we cannot control the logging. There are a lot of logs to the command prompt.
This may be fine for a standalone server, but if we integrate this, it can be quite annoying.
We could add a flag to the configuration?
Does this make sense to you?

**Comment by capaj** [comment]
Yeah, good idea. I will gladly merge such PR.

**Comment by sv2dev** [comment]
All right, I'll create one tonight (UTC+2) ;)

**Comment by sv2dev** [comment]
The PR is raised at #28
