### ISSUE TITLE
required node version not made clear

### ISSUE THREAD

**Issue by henrjk** [capaj/chokidar-socket-emitter#5]
Today I used this module with success inside a grunt connect task to notify the app of changes in javascript file so that systemjs-hot-reloader will reimport modules managed with jspm.

One obstacle was that the code of this module uses ES6 features and I believe this requires node 4+ and could also be compatible with io.js. But I have not researched the io.js specifics.

Perhaps the simplest change would be to tip off the next user by adding

```
  "engines": {
    "node": ">=4"
  },
```

 to `package.json`.

I just read this post about [engines and engineStrict](http://www.marcusoft.net/2015/03/packagejson-and-engines-and-enginestrict.html). 

My summary: The suggested change would result in a warning only at the moment it is **installed as package**. So  `npm install chokidar-socket-emitter` will give warning but not `npm install` when working on this package. 

Adding 

```
  "engineStrict": true.
```

would cause this to result in an error.

I haven't not actually tested the above changes yet. 

An alternative would be to build this component so that it is transpiled to ES5 perhaps when published to npm's public registry. 

In addition this could be mentioned on the README page.

**Comment by capaj** [comment]
I added both to package.json. I think that should suffice. Thanks for the issue.

**Comment by henrjk** [comment]
:thumbsup: Thank you!
